name: Simple Concept Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    APP_NAME: "Todo App"
    ENVIRONMENT: "Production"

jobs:
    Learn:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello World from $APP_NAME"
            - name: step2
              run: echo "This is a simple workflow for $APP_NAME in $ENVIRONMENT"
            - name: step3
              run: |
                  echo "Name of dockerhub username is ${{vars.DOCKER_USERNAME}}"
                  echo "Name of EC2 username is ${{vars.AWS_EC2_USER}}"
                  echo "Name of github repository is ${{github.repository}}"

            - name: step4 checkout
              uses: actions/checkout@v6
            - name: step5 setup-java
              uses: actions/setup-java@v5
              with:
                  java-version: 25
                  distribution: temurin
            - name: step6 run-java
              run: |
                  java -version
